port: 8080

database:
  host:
  port:
  user:
  password:
  dbname:
  sslmode:

auth:
  jwt_secret: secret-key-12345 # for demo purpose, should save in another place
  expire: 24                   # hour

grpc:
  host: waohire-ws-production.up.railway.app
  port: 443

logger:
  path: logs/server.log