port: 8080

database:
  host:
  port:
  user:
  password:
  dbname:
  sslmode:

auth:
  jwt_secret: secret-key-12345 # for demo purpose, should save in another place
  expire: 24                   # hour

ws:
  host: waohire-restful-production.up.railway.app
  port: 50051

logger:
  path: logs/server.log